version: "3.8"

services:
  jsou-tam-body-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jsou-tam-body-api
    ports:
      - "8000:8000"
    restart: unless-stopped

  jsou-tam-body-api-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: jsou-tam-body-api-dev
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    entrypoint: ["./dev-entrypoint.sh"]
    # command:
    #   [
    #     "ghcid",
    #     "--command=stack repl data-api:exe:data-api --allow-different-user  --color always",
    #     "--test=main",
    #   ]
