name: data-api
version: 0.1.0.0
dependencies:
  - base >= 4.7 && < 5
  - servant
  - servant-server
  - wai
  - warp
  - aeson
  - text
  - time
  - wai-cors
  # Add these dependencies for ORISScrapper
  - bytestring
  - http-conduit
  - cassava
  - vector
  - containers
  - filepath
  - directory
  - unordered-containers
  - aeson-pretty

library:
  source-dirs: src
  exposed-modules:
    - Main
    - ORISScrapper

executables:
  data-api:
    main: Main.hs
    source-dirs: src
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
